Ignore error

diff --git a/weekly/handy b/weekly/handy
--- a/weekly/handy
+++ b/weekly/handy
@@ -1,4 +1,12 @@
 #!/bin/bash
 # Copyright © 2012 Martin Ueding <dev@martin-ueding.de>
 
-handy
+set -e
+set -u
+
+if ! handy
+then
+	echo "Probably the card is just missing"
+fi
+
+exit 0
