Fetch all foreign remotes

diff --git a/tasks/maintenance-git-autopush b/tasks/maintenance-git-autopush
--- a/tasks/maintenance-git-autopush
+++ b/tasks/maintenance-git-autopush
@@ -22,8 +22,10 @@ then
 	bold="$(tput bold)"
 
 	blue="$(tput setaf 4)"
+	cyan="$(tput setaf 6)"
 	green="$(tput setaf 2)"
 	orange="$(tput setaf 3)"
+	purple="$(tput setaf 5)"
 	red="$(tput setaf 1)"
 
 	reset="$(tput sgr0)"
@@ -32,6 +34,8 @@ else
 
 	blue=
 	green=
+	cyan=
+	purple=
 	orange=
 	red=
 
@@ -122,6 +126,19 @@ check-folder() {
 		else
 			printf "%s%-8s%s" "${green}" "OK" "${reset}"
 			printf "%-12s %s\n" "$remote" "$foldername"
+		fi
+	done
+
+	for remote in $(git remote)
+	do
+		if ! containsElement "$remote" "${remotes[@]}"
+		then
+			printf "%s%-8s%s" "${cyan}" "FETCH" "${reset}"
+			printf "%-12s %s\n" "$remote" "$foldername"
+			if ! git fetch "$remote"
+			then
+				echo -e "${red}Fetch failed.$reset"
+			fi
 		fi
 	done
 }
